# Based on the sample workflow in Hugo docs at: https://gohugo.io/hosting-and-deployment/hosting-on-github/

name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      # The official example directly installs the Hugo .deb package with a hard-coded version
      # string into the Ubuntu container that's running, but I'm not a huge fan of that so I
      # use the officially-maintained Snap instead so we can always track the latest version.
      #
      # I'd probably rather switch to Fedora and just `dnf install hugo`, but for some reason
      # GitHub Actions still doesn't provide a `fedora-latest` container image in 2024...
      #
      # See: https://snapcraft.io/hugo
      - name: Install Hugo CLI
        run: sudo snap install hugo
      # This step was directly from the example file too, but since my theme doesn't require
      # dart-sass, I don't bother with it to speed up builds and make them more efficient.
      # - name: Install Dart Sass
      #  run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      # I also don't have any Node.js deps, so I've commented this out for now. Might need it
      # again if I ever change to a more complex theme.
      # - name: Install Node.js dependencies
      #  run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: Etc/UTC
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
